<Project Sdk="Microsoft.NET.Sdk.Web">

	<ItemGroup>
		<ProjectReference Include="..\Jarvis.Application\Jarvis.Application.csproj" />
		<ProjectReference Include="..\Jarvis.Infrastructure\Jarvis.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<!-- NAudio permanece, se seu TTS/STT ainda usa -->
		<PackageReference Include="NAudio" Version="2.2.1" />
	</ItemGroup>

	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Include="scripts\tts_edge.py">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</None>
	</ItemGroup>

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

</Project>